

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.



i0 = 1
i1 = 2

sum = 2
while True:
  i2 = i0+i1
  i0 = i1
  i1 = i2
  if i2 >= 4e6:
    break
  if i2 % 2 == 0:
    sum += i2

print(f"Euler 002:\t{sum}")